---
# tasks file for install_apache2
 

- name: CREATE NEW DIR FOR REGISTRY
  file:
    path: "{{ item }}" 
    state: directory
    owner: "{{ user }}"
    mode: '0775'
  with_items:
    - ./docker-registry/auth
    - ./docker-registry/repo  
    - ./docker-registry/certs
          
- name: INSTALL HTPASSWD
  apt: 
    name: "{{ packages }}" 
    update_cache: yes 
    state: latest
  vars:
    packages:
    - apache2-utils
    
- name: CREATE PASSWORD FOR REGISTRY 
  shell: htpasswd -Bbn "{{ user_registry }}" "{{ pass_registry }}" > ./docker-registry/auth/htpasswd

- name: CREATE SELF-SIGNED CERT
  shell: openssl req -new -x509 -days 1461 -nodes -out ./docker-registry/certs/public.pem -keyout ./docker-registry/certs/private.key -subj "/C=RU/ST=SPb/L=SPb/O=Global Security/OU=IT Department/CN="{{ host_registry }}""
       
- name: COPY DAEMON DOCKER FILE TO SERVER
  template:
    src: "files/daemon.json.j2"
    dest: "/etc/docker/daemon.json" 
  notify: RELOAD DOCKER
  
- name: COPY DOCKER-COMPOSE FILE TO SERVER
  template:
    src: "files/docker-compose.yml.j2"
    dest: "./docker-registry/docker-compose.yml"

- name: RUN DOCKER-COMPOSE
  shell: cd ./docker-registry && docker-compose up -d
          
   
      


