---
# defaults file for install_registry

user: "lobofffailodrom"

host_registry: "10.128.0.5"

port_registry: "5000"

user_registry: "admin"

pass_registry: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33373566343932643333383838656565623663333739636539323462303230633036653231616166
          6533346663376364626134633836383735643936303961350a353534363835636634656261303862
          35653831656630613764313933656539383634363031663137393734656631313135623563313165
          3365333735313235370a313563393335656339633333373934636464303661636364623631353431
          6535
    



