---
 - hosts: ci
   become: true
   
   tasks:  
   - name: RUN DOCKER-COMPOSE FOR INSTALL JENKINS
     shell: git clone https://github.com/loboff1/ncdevopsschool22.git && cd ~/ncdevopsschool22/jenkins-install && docker-compose up -d
