version: '3.7'

services:

  webapp:
    container_name: flask
    build: .
    #image: ncdevreg.ml:5000/flask_webapp:$GIT_BRANCH-$BUILD_NUMBER
    user: root
    restart: always
    ports:
      - '5000:80'
    #volumes:
      #- .:/app
    networks:
      - network

networks:
  network:
    driver: bridge
  
