version: '3.7'

services:
  vis:
    image: dockersamples/visualizer
    ports:
      - "5001:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - flask-network
  webapp:
    #container_name: flask
    #build: .
    image: ncdevreg.ml:5000/flask_webapp-$GIT_BRANCH:$BUILD_NUMBER
    user: root
    restart: always
    ports:
      - '5000:80'
    deploy:
      replicas: 2
    #volumes:
      #- .:/app
    networks:
      - flask-network

networks:
  flask-network:
  

#networks:
#  network:
#    driver: bridge
  
