version: '3.7'

services:
  vis:
    image: dockersamples/visualizer
    ports:
      - "5001:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
  webapp:
    image: ncdevreg.ml:5000/flask_webapp-$GIT_BRANCH:$BUILD_NUMBER
    ports:
      - "5555:80"
    volumes:
      - ./database.db:database.db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
