name: Create instances using Terraform

on:
  # Run this workflow manually
  workflow_dispatch:
  
env:
  TERRAFORM_DIR: "terraform"
  CREATE_VM: "-target=google_compute_instance.ncdev"
  
jobs:
  create-instances:
    runs-on: ubuntu-latest
       
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2

    # Authentication via credentials json
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
         credentials_json: '${{ secrets.GCP_CREDENTIALS }}'
       
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: terraform -chdir=./${{ env.TERRAFORM_DIR }} init
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
        
    - name: Terraform Format
      run: terraform fmt -check
  
    - name: Terraform Plan
      run: terraform -chdir=./${{ env.TERRAFORM_DIR }} plan ${{ env.CREATE_VM }}
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Terraform Apply
      run: terraform -chdir=./${{ env.TERRAFORM_DIR }} apply -auto-approve ${{ env.CREATE_VM }}
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'

    - name: Terraform Output
      run: terraform -chdir=./${{ env.TERRAFORM_DIR }} output
      env:
        GOOGLE_CREDENTIALS: '${{ secrets.GCP_CREDENTIALS }}'
