name: Deploy tools to GCP

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  INSTALL_DOCKER_DIR: "ansible"
  INSTALL_JENKINS_DIR: "ansible" 
  KEY_FILENAME: "id_rsa"  
  ANSIBLE_PLAYBOOK_NAME_DOCKER: "playbook.yml"
  ANSIBLE_PLAYBOOK_NAME_JENKINS: "playbook-jenkins.yml"
  HOSTS_INSTALL_DOCKER: "ci-1:dev-1"
  
jobs:
  install-docker:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
   
    # Setup key
    - name: Setup key
      run: | 
           mkdir "$HOME/.ssh"
           echo "${{ secrets.KEY }}" > "$HOME/.ssh/${{ KEY_FILENAME }}"
           chmod 600 "$HOME/.ssh/${{ KEY_FILENAME }}"
 
     # Install Docker to GCP    
    - name:  Install Docker to GCP instances
      run: | 
           cd "./${{ env.INSTALL_DOCKER_DIR }}"
           ansible all -m ping -u "root"
           ansible-playbook ${{ env.ANSIBLE_PLAYBOOK_NAME_DOCKER }} -i hosts -l "${{ env.HOSTS_INSTALL_DOCKER }}"
 
  install-jenkins:
    runs-on: ubuntu-latest
    needs: install-docker
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
   
    # Setup key
    - name: Setup key
      run: | 
           mkdir "$HOME/.ssh"
           echo "${{ secrets.KEY }}" > "$HOME/.ssh/${{ KEY_FILENAME }}"
           chmod 600 "$HOME/.ssh/${{ KEY_FILENAME }}"
           
      # Install Jenkins to GCP      
    - name:  Install Jenkins to GCP instance
      run: | 
           cd "./${{ env.INSTALL_JENKINS_DIR }}"
           ansible-playbook  ${{ env.ANSIBLE_PLAYBOOK_NAME_JENKINS }}
           
           
